version: '3'
services:
  php-fpm:
    build: ./php70-fpm/
    image: php70-fpm:0.1
    restart: always
    expose:
      - 9000
    volumes:
      - ./php70-fpm/etc:/usr/local/etc
      - C:/ws/web:/web
      - C:/ws/Composer:/usr/share/composer
      - C:/ws/Composer/cache:/usr/share/composer/cache
    environment:
      COMPOSER_HOME: /usr/share/composer
      COMPOSER_CACHE_DIR: /usr/share/composer/cache
    container_name: "jyj-fpm"
  nginx:
    image: nginx
    restart: always
    privileged: true
    ports:
      - 18081:80
    links:
      - php-fpm
    volumes:
      - ./nginx15/conf.d:/etc/nginx/conf.d:rw
      - c:/ws/web:/web
    container_name: "jyj-nginx"

