version: '3'
services:
  php-fpm:
    build: ./php70-fpm/
    image: php70-fpm:0.1
    expose:
      - 9000
    volumes:
      - ./php70-fpm/etc:/usr/local/etc
      - /Users/yhl/Desktop/work:/web
      - /Users/yhl/.composer:/usr/share/composer
      - /Users/yhl/.composer/cache:/usr/share/composer/cache
    environment:
      COMPOSER_HOME: /usr/share/composer
      COMPOSER_CACHE_DIR: /usr/share/composer/cache
    container_name: "jyj-fpm"
  nginx:
    image: nginx
    ports:
      - 18081:80
    links:
      - php-fpm
    volumes:
      - ./nginx15/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx15/conf.d:/etc/nginx/conf.d
      - /Users/yhl/Desktop/work:/web
    container_name: "jyj-nginx"

    depends_on:
      - php-fpm

