version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 18080:80
    volumes:
      - "./nginx15/nginx.conf:/etc/nginx/nignx.conf"
      - "./nginx15/conf.d:/etc/nginx/conf.d"
      - "./src:/web"
    links:
      - php-fpm
    container_name : "nginx15"
  php-fpm:
    build: ./php70-fpm/
    image: php70-fpm:0.1
    expose:
      - 9000
    volumes:
      - "./php70-fpm/etc:/usr/local/etc"
      - "./src:/web"
      - "C:/ws/Composer:/usr/share/composer"
      - "C:/ws/Composer/cache:/usr/share/composer/cache"
    environment:
      COMPOSER_HOME: /usr/share/composer
      COMPOSER_CACHE_DIR: /usr/share/composer/cache
    links:
      - mysqld
    container_name : "php70-fpm"
  mysqld:
    image: mysql
    ports:
      - 13306:3306
    expose:
      - 3306
    volumes:
      - "./mysql8/config/mysql:/etc/mysql"
      - "./mysql8/data/mysql:/var/lib/mysql"
    container_name : "mysql8"
    environment:
      MYSQL_ROOT_PASSWORD: 123456