FROM php:7.3.4-cli
COPY ./composer.phar /usr/local/bin/composer
COPY ./swoole-src-master.tar.gz /build/swoole.tar.gz
COPY ./mongodb-1.5.3.tgz /build/mongodb-1.5.3.tgz
ENV COMPOSER_HOEM /user/share/composer
ENV COMPOSER_CACHE_DIR /user/share/composer/cache
RUN chmod +x /usr/local/bin/composer && \
    rm -rf /etc/apt/source.list && \
    echo deb http://mirrors.aliyun.com/debian stretch main contrib non-free > /etc/apt/sources.list && \
    echo deb http://mirrors.aliyun.com/debian stretch-proposed-updates main contrib non-free >> /etc/apt/sources.list && \
    echo deb http://mirrors.aliyun.com/debian stretch-updates main contrib non-free >> /etc/apt/sources.list && \
    echo deb-src http://mirrors.aliyun.com/debian stretch main contrib non-free >> /etc/apt/sources.list && \
    echo deb-src http://mirrors.aliyun.com/debian stretch-proposed-updates main contrib non-free >> /etc/apt/sources.list && \
    echo deb-src http://mirrors.aliyun.com/debian stretch-updates main contrib non-free >> /etc/apt/sources.list && \
    echo deb http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib >> /etc/apt/sources.list && \
    echo deb-src http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y zlib1g-dev && \
    apt-get install -y libssl-dev && \
    apt-get install -y libnghttp2-dev && \
    apt-get install -y libhiredis-dev && \
    apt-get install -y libzip-dev && \
    docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip && \
    docker-php-ext-install sockets && \
    pecl install -O /build/mongodb-1.5.3.tgz && \
    echo extension=mongodb.so > /usr/local/etc/php/conf.d/mongodb.ini && \
    cd /build && \
    rm -rf ./swoole-src && \
    tar zxvf ./swoole.tar.gz && \
    mv swoole-src* swoole-src && \
    cd swoole-src && \
    phpize && \
    ./configure \
        --enable-openssl  \
        --enable-http2  \
        --enable-async-redis \
        --enable-mysqlnd  \
        --enable-sockets  && \
    make clean && make && make install && \
    echo extension=swoole.so > /usr/local/etc/php/conf.d/swoole.ini && \
    rm -rf /build && \
    cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    mkdir -p /usr/share/composer/cache && \
    mkdir -p /app && \
    cd /app &&\
    composer config -g repo.packagist composer https://packagist.phpcomposer.com && \
    composer require easyswoole/easyswoole -vvv && \
    php vendor/bin/easyswoole install && \
    composer clear-cache && \
EXPOSE 9501
ENTRYPOINT ["php", "/var/www/code/easyswoole", "start"]