version: '3'
services:
  easy-swoole:
    build: ./php73-swoole/easy-swoole
    image: easy-swoole:0.1
    expose:
      - 9501
    volumes:
      - ./php73-swoole/etc/php:/usr/local/etc/php
      - ./src:/app
      - C:/ws/Composer:/usr/share/composer
      - C:/ws/Composer/cache:/usr/share/composer/cache
    environment:
      COMPOSER_HOME: /usr/share/composer
      COMPOSER_CACHE_DIR: /usr/share/composer/cache
    container_name: "easy-swoole"
    entrypoint: /app/easyswoole start
  nginx:
    image: nginx
    ports:
      - 18082:80
    links:
      - easy-swoole
    volumes:
      - ./nginx15/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx15/conf.d:/etc/nginx/conf.d
      - ./src:/app
    container_name: "swoole-nginx"


